/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-11 07:53:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/E:/bookingtour/product/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLXB/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/E:/bookingtour/product/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLXB/WEB-INF/lib/jstl-impl.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1682272410279L));
    _jspx_dependants.put("/WEB-INF/views/home/../includes/Navbarc1.jsp", Long.valueOf(1686430393601L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>Admin quản lý du lịch</title>\r\n");
      out.write("<style>\r\n");
      out.write("	img{\r\n");
      out.write("	max-height:500px;\r\n");
      out.write("	max-width:1200px\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write(" <style>\r\n");
      out.write("          * {\r\n");
      out.write("            box-sizing:border-box\r\n");
      out.write("          }\r\n");
      out.write("          h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("          }\r\n");
      out.write("          /* Slideshow container */\r\n");
      out.write("          .slideshow-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            max-heigth:500px;\r\n");
      out.write("          }\r\n");
      out.write("          /* Ẩn các slider */\r\n");
      out.write("          .mySlides {\r\n");
      out.write("              display: none;\r\n");
      out.write("          }\r\n");
      out.write("          /* Định dạng nội dung Caption */\r\n");
      out.write("          .text {\r\n");
      out.write("            color: #f2f2f2;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 8px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          /* định dạng các chấm chuyển đổi các slide */\r\n");
      out.write("          .dot {\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("            height: 13px;\r\n");
      out.write("            width: 13px;\r\n");
      out.write("            margin: 0 2px;\r\n");
      out.write("            background-color: #bbb;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            transition: background-color 0.6s ease;\r\n");
      out.write("          }\r\n");
      out.write("          /* khi được hover, active đổi màu nền */\r\n");
      out.write("          .active, .dot:hover {\r\n");
      out.write("            background-color: #717171;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          /* Thêm hiệu ứng khi chuyển đổi các slide */\r\n");
      out.write("          .fade {\r\n");
      out.write("            -webkit-animation-name: fade;\r\n");
      out.write("            -webkit-animation-duration: 3s;\r\n");
      out.write("            animation-name: fade;\r\n");
      out.write("            animation-duration: 3s;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          @-webkit-keyframes fade {\r\n");
      out.write("            from {opacity: .4} \r\n");
      out.write("            to {opacity: 1}\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          @keyframes fade {\r\n");
      out.write("            from {opacity: .4} \r\n");
      out.write("            to {opacity: 1}\r\n");
      out.write("          }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row flex-nowrap\">\r\n");
      out.write("		\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <div class=\"col-auto col-md-3 col-xl-2 px-sm-2 px-0t bg-primary\">\r\n");
      out.write("            <div class=\"d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 \">\r\n");
      out.write("                <a href=\"#\" class=\"d-flex align-items-center pb-5 pt-5 mb-md-0 me-md-auto text-white text-decoration-none\">\r\n");
      out.write("                    <span class=\"fs-5 d-none d-sm-inline\">QUẢN LÝ XE BUS</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start \" id=\"menu\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"homeshow.htm\" class=\"nav-link text-white align-middle px-0\">\r\n");
      out.write("                           <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("                            <span class=\"ms-1 d-none d-sm-inline\">Home</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <li><a href=\"danhsachnhanvien.htm\" \r\n");
      out.write("							class=\"nav-link text-white px-0 align-middle\">\r\n");
      out.write("							<i class=\"fa-regular fa-calendar-days\"></i> <span\r\n");
      out.write("								class=\"ms-1 d-none d-sm-inline\">Danh sách nhân viên</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						     </li>\r\n");
      out.write("                 <!--  <li><button onclick=\"goHome()\">Go to Intro Page</button></li> -->\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#submenu2\" data-bs-toggle=\"collapse\" class=\"nav-link text-white px-0 align-middle \">\r\n");
      out.write("                            <i class=\"fa-solid fa-map-location-dot\"></i>\r\n");
      out.write("                            <span class=\"ms-1 d-none d-sm-inline\">Quản lí xe buýt</span></a>\r\n");
      out.write("                        <ul class=\"collapse nav flex-column ms-1\" id=\"submenu2\" data-bs-parent=\"#menu\">\r\n");
      out.write("                            <li class=\"w-100\">\r\n");
      out.write("                                <a href=\"dstuyenduong.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Tuyến đường</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"dsxe.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Xe</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                               <li>\r\n");
      out.write("                                <a href=\"dstramxe.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Trạm xe</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"dstramve.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Trạm vé</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"#submenu3\" data-bs-toggle=\"collapse\" class=\"nav-link text-white px-0 align-middle \">\r\n");
      out.write("                           <i class=\"fa-solid fa-sack-dollar\"></i>\r\n");
      out.write("                            <span class=\"ms-1 d-none d-sm-inline\">Quản lý chung</span></a>\r\n");
      out.write("                        <ul class=\"collapse nav flex-column ms-1\" id=\"submenu3\" data-bs-parent=\"#menu\">\r\n");
      out.write("                            <li class=\"w-100\">\r\n");
      out.write("                                <a href=\"doanhthu.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Doanh thu</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"dsgiave.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Giá vé</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"lichsunhap.htm\" class=\"nav-link text-white px-0\"> <span class=\"d-none d-sm-inline\">Lịch sử nhập doanh thu</span></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                <hr>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("              \r\n");
      out.write("                <div class=\"dropdown pb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle\" id=\"dropdownUser1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        <img src=\"https://github.com/mdo.png\" alt=\"hugenerd\" width=\"30\" height=\"30\" class=\"rounded-circle\">\r\n");
      out.write("                        <span class=\"d-none d-sm-inline mx-1\">Tài khoản</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\">\r\n");
      out.write("   \r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"suattcanhan.htm\">Chỉnh sửa thông tin cá nhân</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"doimatkhau.htm\">Đổi mật khẩu</a></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"logout.htm\">Đăng xuất</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("     <script>\r\n");
      out.write("    /* function goHome() {\r\n");
      out.write("        window.location.href = \"danhsachnhanvien.htm\";\r\n");
      out.write("    } */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write(" \r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 <div class=\"col py-3\">\r\n");
      out.write("	\r\n");
      out.write("	<marquee style=\"border:#007bff 1px SOLID\">Luôn tận tâm trên mọi nẻo đường</marquee>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"slideshow-container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("          <img src=\"images/logo1.jpg\" style=\"width:100%\">\r\n");
      out.write("          <!-- <div class=\"text\">Nội dung caption của slide đầu tiên!</div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("          <img src=\"images/logo2.jpg\" style=\"width:100%\">\r\n");
      out.write("          <!-- <div class=\"text\">Nội dung caption của slide thứ 2!</div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("          <img src=\"images/logo3.jpg\" style=\"width:100%\">\r\n");
      out.write("         <!--  <div class=\"text\">Nội dung caption của slide thứ 3!</div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("      <div style=\"text-align:center;margin: auto;\">\r\n");
      out.write("        <span class=\"dot\" onclick=\"currentSlide(0)\"></span> \r\n");
      out.write("        <span class=\"dot\" onclick=\"currentSlide(1)\"></span> \r\n");
      out.write("        <span class=\"dot\" onclick=\"currentSlide(2)\"></span> \r\n");
      out.write("      </div>  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("    </body>\r\n");
      out.write("    <script>\r\n");
      out.write("      //khai báo biến slideIndex đại diện cho slide hiện tại\r\n");
      out.write("      var slideIndex;\r\n");
      out.write("      // KHai bào hàm hiển thị slide\r\n");
      out.write("      function showSlides() {\r\n");
      out.write("          var i;\r\n");
      out.write("          var slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("          var dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("          for (i = 0; i < slides.length; i++) {\r\n");
      out.write("             slides[i].style.display = \"none\";  \r\n");
      out.write("          }\r\n");
      out.write("          for (i = 0; i < dots.length; i++) {\r\n");
      out.write("              dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          slides[slideIndex].style.display = \"block\";  \r\n");
      out.write("          dots[slideIndex].className += \" active\";\r\n");
      out.write("          //chuyển đến slide tiếp theo\r\n");
      out.write("          slideIndex++;\r\n");
      out.write("          //nếu đang ở slide cuối cùng thì chuyển về slide đầu\r\n");
      out.write("          if (slideIndex > slides.length - 1) {\r\n");
      out.write("            slideIndex = 0\r\n");
      out.write("          }    \r\n");
      out.write("          //tự động chuyển đổi slide sau 5s\r\n");
      out.write("          setTimeout(showSlides, 5000);\r\n");
      out.write("      }\r\n");
      out.write("      //mặc định hiển thị slide đầu tiên \r\n");
      out.write("      showSlides(slideIndex = 0);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      function currentSlide(n) {\r\n");
      out.write("        showSlides(slideIndex = n);\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
